name: Vexcty
version: '${project.version}'
main: com.moonsworkshop.vexcty.Vexcty
authors: [ MoonsWorkshop ]
description: 1.8 Version of Vexcty
website: github.com/MOONSWORKSHOPLLC
commands:
  grant:
  test:
  punish:
  rank:
  lang:
  admin:
  v:
    aliases: vanish
  version:
    aliases: ver
  addvelocitytoall:
    aliases:
      - avta
  addvelocitytoplayer:
    aliases:
      - avtp
  ip:

