name: Vexcty
version: '${project.version}'
main: com.moonsworkshop.vexcty.Vexcty
authors: [ MoonsWorkshop ]
description: 1.8 Version of Vexcty
website: github.com/MOONSWORKSHOPLLC
commands:
  test:
  punish:
  rank:
  lang:
